services:
    nginx:
        build:
          context: ./nginx/
          dockerfile: Dockerfile.nginx
        ports:
          - "80:80"
        depends_on:
          - backend
        volumes:
          - static_volume:/app/django_static
    backend:
        restart: unless-stopped
        build: .
        entrypoint: /app/server-entrypoint.sh
        volumes:
            - static_volume:/app/django_static
            - ./db.sqlite3:/app/db.sqlite3
            - ./media:/app/media 
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - redis

    worker:
        restart: unless-stopped
        build: . 
        entrypoint: /app/worker-entrypoint.sh
        volumes:
            - static_volume:/app/django_static
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
        depends_on:
            - backend
            - redis
    beat:
        restart: unless-stopped
        build: . 
        entrypoint: /app/beat-entrypoint.sh
        volumes:
            - static_volume:/app/django_static
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
        depends_on:
            - backend
            - redis
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine 
        expose:
            - 6379
    
    
    
    
volumes:
    static_volume: {}

    